name: Unit Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Logic testing
        run: pytest -v tests/test_logic.py